"""
## ServiceKey is 6B2866C8FD500001 ##
ServiceId_GenHC_Ecomm = "3CF9E00001"
MPID_NGT_SBX = "Kyle Test"


"""
ServiceId_TRN_SBX = "372EC00001"
MPID_TRN_SBX = "TRN_Ecommerce_SBX"
# ServiceKey is 4DBA36C8FD500001
ServiceId_GenHC_Ecomm = "35EDC00001"
MPID_GenHC_Ecomm = "Generic_Ecomm_HC"

TPSTestCases = {
                "CustBillingAddress1" : {"ServiceId":ServiceId_GenHC_Ecomm,
                                         "MerchantProfileId":MPID_GenHC_Ecomm,
                                         "ShippingData":None,
                                         "Address":{"Street1":"1st","City":"Denver","StateProvince":"CO","PostalCode":"80202","CountryCode":"USA"},                                         
                                         "EMVData":None,
                                         "ApplicationConfigurationData":None,
                                         "CardSecurityData":None,
                                         "EcommerceSecurityData":None,
                                         "AlternativeMerchantData":None,
                                         "Level2Data":None,
                                         "InterchangeData":None
                                         },
                "CustBillingAddress2" : {"ServiceId":ServiceId_GenHC_Ecomm,
                                         "MerchantProfileId":MPID_GenHC_Ecomm,
                                         "ShippingData":None,
                                         "Address":{"Street1":None,"City":None,"StateProvince":"CO","PostalCode":None,"CountryCode":None},                                         
                                         "EMVData":None,
                                         "ApplicationConfigurationData":None,
                                         "CardSecurityData":None,
                                         "EcommerceSecurityData":None,
                                         "AlternativeMerchantData":None,
                                         "Level2Data":None,
                                         "InterchangeData":None
                                         },
                "CustShippingAddress1" : {"ServiceId":ServiceId_GenHC_Ecomm,
                                         "MerchantProfileId":MPID_GenHC_Ecomm,
                                         "BillingData":None,
                                         "Address":{"Street1":"1st","City":"Denver","StateProvince":"CO","PostalCode":"80202","CountryCode":"USA"},                                        
                                         "EMVData":None,
                                         "ApplicationConfigurationData":None,
                                         "CardSecurityData":None,
                                         "EcommerceSecurityData":None,
                                         "AlternativeMerchantData":None,
                                         "Level2Data":None,
                                         "InterchangeData":None
                                         },
                "CustShippingAddress2" : {"ServiceId":ServiceId_GenHC_Ecomm,
                                         "MerchantProfileId":MPID_GenHC_Ecomm,
                                         "BillingData":None,
                                         "Address":{"Street1":None,"City":None,"StateProvince":"CO","PostalCode":None,"CountryCode":None},                                         
                                         "EMVData":None,
                                         "ApplicationConfigurationData":None,
                                         "CardSecurityData":None,
                                         "EcommerceSecurityData":None,
                                         "AlternativeMerchantData":None,
                                         "Level2Data":None,
                                         "InterchangeData":None
                                         },
                "CustIntlBillingAddress1" :  {"ServiceId":ServiceId_TRN_SBX,
                                             "MerchantProfileId":MPID_TRN_SBX,
                                             "ShippingData":None,
                                             "InternationalAddress":{"HouseNumber":"1234","Street1":"1st","City":"Denver","StateProvince":"CO","PostalCode":"80202","CountryCode":"USA"},                                         
                                             "EMVData":None,
                                             "ApplicationConfigurationData":None,
                                             "CVData":"123",
                                             "CVDataProvided":"Provided",
                                             "AVSData":None,
                                             "InternationalAVSData":None,
                                             "EcommerceSecurityData":None,
                                             "AlternativeMerchantData":None,
                                             "Level2Data":None,
                                             "InterchangeData":None
                                             },
                "CustIntlBillingAddress2" :  {"ServiceId":ServiceId_TRN_SBX,
                                             "MerchantProfileId":MPID_TRN_SBX,
                                             "ShippingData":None,
                                             "InternationalAddress":{"HouseNumber":"1234","Street1":None,"City":None,"StateProvince":"CO","PostalCode":None,"CountryCode":None},                                         
                                             "EMVData":None,
                                             "ApplicationConfigurationData":None,
                                             "CVData":"123",
                                             "CVDataProvided":"Provided",
                                             "AVSData":None,
                                             "InternationalAVSData":None,
                                             "EcommerceSecurityData":None,
                                             "AlternativeMerchantData":None,
                                             "Level2Data":None,
                                             "InterchangeData":None
                                             },
             "CustIntlShippingAddress1" :  {"ServiceId":ServiceId_TRN_SBX,
                                             "MerchantProfileId":MPID_TRN_SBX,
                                             "BillingData":None,
                                             "InternationalAddress":{"HouseNumber":"1234","Street1":"1st","City":"Denver","StateProvince":"CO","PostalCode":"80202","CountryCode":"USA"},                                         
                                             "EMVData":None,
                                             "ApplicationConfigurationData":None,
                                             "CVData":"123",
                                             "CVDataProvided":"Provided",
                                             "AVSData":None,
                                             "InternationalAVSData":None,
                                             "EcommerceSecurityData":None,
                                             "AlternativeMerchantData":None,
                                             "Level2Data":None,
                                             "InterchangeData":None
                                             },
             "CustIntlShippingAddress2" :  {"ServiceId":ServiceId_TRN_SBX,
                                             "MerchantProfileId":MPID_TRN_SBX,
                                             "BillingData":None,
                                             "InternationalAddress":{"HouseNumber":"1234","Street1":None,"City":None,"StateProvince":"CO","PostalCode":None,"CountryCode":None},                                         
                                             "EMVData":None,
                                             "ApplicationConfigurationData":None,
                                             "CVData":"123",
                                             "CVDataProvided":"Provided",
                                             "AVSData":None,
                                             "InternationalAVSData":None,
                                             "EcommerceSecurityData":None,
                                             "AlternativeMerchantData":None,
                                             "Level2Data":None,
                                             "InterchangeData":None
                                             },
             "IntlAVS1" :  {"ServiceId":ServiceId_TRN_SBX,
                                "MerchantProfileId":MPID_TRN_SBX,
                                "CustomerData":None,                                        
                                "EMVData":None,
                                "ApplicationConfigurationData":None,
                                "CVData":"123",
                                "CVDataProvided":"Provided",
                                "AVSData":None,
                                "InternationalAVSData":{"HouseNumber":"1234","Street":"1st","City":"Denver","StateProvince":"CO","PostalCode":"80202","Country":"USA"},
                                "EcommerceSecurityData":None,
                                "AlternativeMerchantData":None,
                                "Level2Data":None,
                                "InterchangeData":None
                                },
             "IntlAVS2" :  {"ServiceId":ServiceId_TRN_SBX,
                                "MerchantProfileId":MPID_TRN_SBX,
                                "CustomerData":None,                                        
                                "EMVData":None,
                                "ApplicationConfigurationData":None,
                                "CVData":"123",
                                "CVDataProvided":"Provided",
                                "AVSData":None,
                                "InternationalAVSData":{"HouseNumber":None,"Street":None,"City":None,"StateProvince":"CO","PostalCode":None,"Country":None},
                                "EcommerceSecurityData":None,
                                "AlternativeMerchantData":None,
                                "Level2Data":None,
                                "InterchangeData":None
                                },
             "AccountType1" : {"ServiceId":ServiceId_GenHC_Ecomm,
                               "MerchantProfileId":MPID_GenHC_Ecomm,
                                "CustomerData":None,                                                                                 
                                "EMVData":None,
                                "ApplicationConfigurationData":None,
                                "PIN":"D8BC0FAF9BBD9B17",
                                "KeySerialNumber":"856290000060027C",
                                "EcommerceSecurityData":None,
                                "AccountType":"CheckingAccount",
                                "AlternativeMerchantData":None,
                                "Level2Data":None,
                                "InterchangeData":None
                                },
             "AccountType2" : {"ServiceId":ServiceId_GenHC_Ecomm,
                               "MerchantProfileId":MPID_GenHC_Ecomm,
                                "CustomerData":None,                                                                                 
                                "EMVData":None,
                                "ApplicationConfigurationData":None,
                                "PIN":"D8BC0FAF9BBD9B17",
                                "KeySerialNumber":"856290000060027C",
                                "EcommerceSecurityData":None,
                                "AccountType":None,
                                "AlternativeMerchantData":None,
                                "Level2Data":None,
                                "InterchangeData":None
                                },
             "SigCaptured" : {"ServiceId":ServiceId_GenHC_Ecomm,
                                         "MerchantProfileId":MPID_GenHC_Ecomm,
                                         "ShippingData":None,
                                         "Address":{"Street1":"1st","City":"Denver","StateProvince":"CO","PostalCode":"80202","CountryCode":"USA"},                                         
                                         "EMVData":None,
                                         "ApplicationConfigurationData":None,
                                         "CardSecurityData":None,
                                         "EcommerceSecurityData":None,
                                         "AlternativeMerchantData":None,
                                         "SignatureCaptured":False,
                                         "Level2Data":None,
                                         "InterchangeData":None
                                         },
            "EcommSecurityData":  { "ServiceId":"911C800001",
                                    "MerchantProfileId":"EcommMerch",
                                    "ShippingData":None,
                                    "Address":{"Street1":"1st","City":"Denver","StateProvince":"CO","PostalCode":"80202","CountryCode":"USA"},                                         
                                    "EMVData":None,
                                    "ApplicationConfigurationData":None,
                                    "CardSecurityData":None,                                    
                                    "AlternativeMerchantData":None,
                                    "Level2Data":None,
                                    "TokenData":"01234567890123456789",
                                    "TokenIndicator":"VPAS",
                                    "InterchangeData":None
                                    },
                "CustPresent" : {"ServiceId":"39C6700001",
                                 "ApplicationProfileId":"4815",
                                         "MerchantProfileId":"test_10",
                                         "ShippingData":None,
                                         "Address":{"Street1":"1st","City":"Denver","StateProvince":"CO","PostalCode":"80202","CountryCode":"USA"},                                         
                                         "EMVData":None,
                                         "ApplicationConfigurationData":None,
                                         "CardSecurityData":None,
                                         "EcommerceSecurityData":None,
                                         "AlternativeMerchantData":None,
                                         "Level2Data":None,
                                         "CustomerPresent":"NotSet",
                                         "InterchangeData":None
                                         }
             
            }