## ServiceKey is 6B2866C8FD500001 ##
ServiceId_NGT_SBX = "3CF9E00001"
MPID_NGT_SBX = "Kyle Test"

ServiceId_TRN_SBX = "372EC00001"
MPID_TRN_SBX = "TRN_Ecommerce_SBX"

TestCases = {
                "CustBillingAddress1" : {"ServiceId":ServiceId_NGT_SBX,
                                         "MerchantProfileId":MPID_NGT_SBX,
                                         "ShippingData":None,
                                         "Address":{"Street1":"1st","City":"Denver","StateProvince":"CO","PostalCode":"80202","CountryCode":"USA"},                                         
                                         "EMVData":None,
                                         "ApplicationConfigurationData":None,
                                         "CardSecurityData":None,
                                         "EcommerceSecurityData":None
                                         },
                "CustBillingAddress2" : {"ServiceId":ServiceId_NGT_SBX,
                                         "MerchantProfileId":MPID_NGT_SBX,
                                         "ShippingData":None,
                                         "Address":{"Street1":None,"City":None,"StateProvince":"CO","PostalCode":None,"CountryCode":None},                                         
                                         "EMVData":None,
                                         "ApplicationConfigurationData":None,
                                         "CardSecurityData":None,
                                         "EcommerceSecurityData":None
                                         },
                "CustShippingAddress1" : {"ServiceId":ServiceId_NGT_SBX,
                                         "MerchantProfileId":MPID_NGT_SBX,
                                         "BillingData":None,
                                         "Address":{"Street1":"1st","City":"Denver","StateProvince":"CO","PostalCode":"80202","CountryCode":"USA"},                                        
                                         "EMVData":None,
                                         "ApplicationConfigurationData":None,
                                         "CardSecurityData":None,
                                         "EcommerceSecurityData":None
                                         },
                "CustShippingAddress2" : {"ServiceId":ServiceId_NGT_SBX,
                                         "MerchantProfileId":MPID_NGT_SBX,
                                         "BillingData":None,
                                         "Address":{"Street1":None,"City":None,"StateProvince":"CO","PostalCode":None,"CountryCode":None},                                         
                                         "EMVData":None,
                                         "ApplicationConfigurationData":None,
                                         "CardSecurityData":None,
                                         "EcommerceSecurityData":None
                                         },
                "CustIntlBillingAddress1" :  {"ServiceId":ServiceId_TRN_SBX,
                                             "MerchantProfileId":MPID_TRN_SBX,
                                             "ShippingData":None,
                                             "InternationalAddress":{"HouseNumber":"1234","Street1":"1st","City":"Denver","StateProvince":"CO","PostalCode":"80202","CountryCode":"USA"},                                         
                                             "EMVData":None,
                                             "ApplicationConfigurationData":None,
                                             "CVData":"123",
                                             "CVDataProvided":"Provided",
                                             "AVSData":None,
                                             "InternationalAVSData":None,
                                             "EcommerceSecurityData":None
                                             },
                "CustIntlBillingAddress2" :  {"ServiceId":ServiceId_TRN_SBX,
                                             "MerchantProfileId":MPID_TRN_SBX,
                                             "ShippingData":None,
                                             "InternationalAddress":{"HouseNumber":"1234","Street1":None,"City":None,"StateProvince":"CO","PostalCode":None,"CountryCode":None},                                         
                                             "EMVData":None,
                                             "ApplicationConfigurationData":None,
                                             "CVData":"123",
                                             "CVDataProvided":"Provided",
                                             "AVSData":None,
                                             "InternationalAVSData":None,
                                             "EcommerceSecurityData":None
                                             },
             "CustIntlShippingAddress1" :  {"ServiceId":ServiceId_TRN_SBX,
                                             "MerchantProfileId":MPID_TRN_SBX,
                                             "BillingData":None,
                                             "InternationalAddress":{"HouseNumber":"1234","Street1":"1st","City":"Denver","StateProvince":"CO","PostalCode":"80202","CountryCode":"USA"},                                         
                                             "EMVData":None,
                                             "ApplicationConfigurationData":None,
                                             "CVData":"123",
                                             "CVDataProvided":"Provided",
                                             "AVSData":None,
                                             "InternationalAVSData":None,
                                             "EcommerceSecurityData":None
                                             },
             "CustIntlShippingAddress2" :  {"ServiceId":ServiceId_TRN_SBX,
                                             "MerchantProfileId":MPID_TRN_SBX,
                                             "BillingData":None,
                                             "InternationalAddress":{"HouseNumber":"1234","Street1":None,"City":None,"StateProvince":"CO","PostalCode":None,"CountryCode":None},                                         
                                             "EMVData":None,
                                             "ApplicationConfigurationData":None,
                                             "CVData":"123",
                                             "CVDataProvided":"Provided",
                                             "AVSData":None,
                                             "InternationalAVSData":None,
                                             "EcommerceSecurityData":None
                                             },
             "IntlAVS1" :  {"ServiceId":ServiceId_TRN_SBX,
                                "MerchantProfileId":MPID_TRN_SBX,
                                "CustomerData":None,                                        
                                "EMVData":None,
                                "ApplicationConfigurationData":None,
                                "CVData":"123",
                                "CVDataProvided":"Provided",
                                "AVSData":None,
                                "InternationalAVSData":{"HouseNumber":"1234","Street":"1st","City":"Denver","StateProvince":"CO","PostalCode":"80202","Country":"USA"},
                                "EcommerceSecurityData":None
                                },
             "IntlAVS2" :  {"ServiceId":ServiceId_TRN_SBX,
                                "MerchantProfileId":MPID_TRN_SBX,
                                "CustomerData":None,                                        
                                "EMVData":None,
                                "ApplicationConfigurationData":None,
                                "CVData":"123",
                                "CVDataProvided":"Provided",
                                "AVSData":None,
                                "InternationalAVSData":{"HouseNumber":None,"Street":None,"City":None,"StateProvince":"CO","PostalCode":None,"Country":None},
                                "EcommerceSecurityData":None
                                },
             "AccountType1" : {"ServiceId":ServiceId_NGT_SBX,
                               "MerchantProfileId":MPID_NGT_SBX,
                                "CustomerData":None,                                                                                 
                                "EMVData":None,
                                "ApplicationConfigurationData":None,
                                "PIN":"D8BC0FAF9BBD9B17",
                                "KeySerialNumber":"856290000060027C",
                                "EcommerceSecurityData":None,
                                "AccountType":"CheckingAccount"
                                },
             "AccountType2" : {"ServiceId":ServiceId_NGT_SBX,
                               "MerchantProfileId":MPID_NGT_SBX,
                                "CustomerData":None,                                                                                 
                                "EMVData":None,
                                "ApplicationConfigurationData":None,
                                "PIN":"D8BC0FAF9BBD9B17",
                                "KeySerialNumber":"856290000060027C",
                                "EcommerceSecurityData":None,
                                "AccountType":None
                                }
             
            }